// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClfCbxBJPK9CpbcysdFR9BkviR2gjPrK0',
    appId: '1:867097941222:web:0dd5b2306baca4712d1727',
    messagingSenderId: '867097941222',
    projectId: 'chat-app-91297',
    authDomain: 'chat-app-91297.firebaseapp.com',
    storageBucket: 'chat-app-91297.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4kMm1GyvdYVu0GfCraMfsMT4l6BUlN-A',
    appId: '1:867097941222:android:0e3c7e858dc79e4d2d1727',
    messagingSenderId: '867097941222',
    projectId: 'chat-app-91297',
    storageBucket: 'chat-app-91297.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWxsi_Vr2p2fDNMO3dG2-arYvd5rg4oDk',
    appId: '1:867097941222:ios:d464976d56da3daa2d1727',
    messagingSenderId: '867097941222',
    projectId: 'chat-app-91297',
    storageBucket: 'chat-app-91297.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWxsi_Vr2p2fDNMO3dG2-arYvd5rg4oDk',
    appId: '1:867097941222:ios:d464976d56da3daa2d1727',
    messagingSenderId: '867097941222',
    projectId: 'chat-app-91297',
    storageBucket: 'chat-app-91297.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClfCbxBJPK9CpbcysdFR9BkviR2gjPrK0',
    appId: '1:867097941222:web:90d9c80659cef9e12d1727',
    messagingSenderId: '867097941222',
    projectId: 'chat-app-91297',
    authDomain: 'chat-app-91297.firebaseapp.com',
    storageBucket: 'chat-app-91297.appspot.com',
  );

}